source 'https://ruby.taobao.org'
gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
 gem 'unicorn', '~> 4.9.0'
gem 'capistrano', '~> 3.4.0'
gem 'capistrano-rails', '~> 1.1'
gem 'capistrano3-unicorn', '~> 0.2.1'
group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'quiet_assets'
  gem 'rails_best_practices', '~> 1.15.7'
  gem 'rails-erd', '~> 1.4.2'
  gem 'faker'
end
gem "twitter-bootstrap-rails"
gem 'devise'
gem 'aasm', '~> 4.2.0'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'wkhtmltopdf-binary-edge', '~> 0.12.2.1'
gem 'pdfkit', '~> 0.8.2'
gem 'actionpack-xml_parser'
gem "faraday"
gem 'certified'
gem 'config'
gem 'will_paginate-bootstrap', '~> 1.0.1'
gem 'strip_attributes'
gem 'acts_as_paranoid', github: 'ActsAsParanoid/acts_as_paranoid'
gem "wysiwyg-rails"
# Markdown 格式 & 文本处理
gem 'redcarpet', '~> 3.2.3'
gem 'rouge', '~> 1.8.0'
gem 'auto-space', '0.0.4'
gem 'nokogiri', '1.6.5'
gem 'rails_autolink', '>= 1.1.0'
gem 'md_emoji', '1.0.2'
gem 'exception_notification'
gem 'truncate_html'
gem 'closure_tree'
gem 'bootstrap-datepicker-rails', :require => 'bootstrap-datepicker-rails', :git => 'git://github.com/Nerian/bootstrap-datepicker-rails.git'
gem 'axlsx'
gem 'axlsx_rails'
