# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a21836853d9d5192cc246fa99355243571dd25902200dc3785174250924a43d9f73d2c7a326de5206c95c79ec28c9d17fbf809f5915ba7d3a3530fe1d3b8a6f

test:
  secret_key_base: 4d01beb939ad5c28d5ac08060b53f0a466af781e74ebb47fd29baa41fd2016c4487de0224d6ab77ceddf92c3255651ce4246cef7fd3305b7b45ed2a710b79376

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
