defaults: &defaults
  open:
    key: wx6664cd85e3fa1aa6
    secret: 87c7009f35ab8c4451664071216a4f8f
  mp:
    appid: wx0a1606a79489a89c
    secret: 046851a0cf0a758c97f7426b8f57443a
    url: https://api.weixin.qq.com
    callback_url: zpdaren.ngrok.cc
    message_templates:
      resume_status_change_template_id: 8Lsk_xjzj8y6EAe4Mo1tzAYr-O4PUglc-j3mlWi5Kvc
      delivery_award_template_id: s-KsdEK9aRRPmg3VA7p3AzPXdsasK-MKpnOvbWHqIzM

development:
  <<: *defaults

test:
  <<: *defaults

production:
  open:
    key: <%= ENV["OPEN_APP_ID"] %>
    secret: <%= ENV["OPEN_APP_SECRET"] %>
  mp:
    appid: <%= ENV["MP_APP_ID"] %>
    secret: <%= ENV["MP_APP_SECRET"] %>
    url: https://api.weixin.qq.com
    callback_url: <%= ENV["MP_CALLBACK_URL"] %>
    message_templates:
      resume_status_change_template_id: <%= ENV["RESUME_STATUS_CHANGE_TEMPLATE_ID"] %>
      delivery_award_template_id: <%= ENV["DELIVERY_AWARD_TEMPLATE_ID"] %>
