development:
  key: wx6664cd85e3fa1aa6
  secret: 87c7009f35ab8c4451664071216a4f8f

production:
  key: wx43c6e09b6b423c06
  secret: c2cce2aa16a011486c1337fdf6f598ef

mp:
  appid: wx0e604319f74644b3
  secret: 89a7ebf45ee66181dfd5bb7cbe1d646c
  url: https://api.weixin.qq.com
  callback_url: zpdaren.com
  message_templates:
    resume_status_change_template_id: <%= ENV["RESUME_STATUS_CHANGE_TEMPLATE_ID"] %>
    delivery_award_template_id: <%= ENV["DELIVERY_AWARD_TEMPLATE_ID"] %>
