development:
  key: wx6664cd85e3fa1aa6
  secret: 87c7009f35ab8c4451664071216a4f8f

production:
  key: <%= ENV["APP_ID"] %>
  secret: <%= ENV["APP_SECRET"] %>

mp:
  appid: <%= ENV["MP_APP_ID"] %>
  secret: <%= ENV["MP_APP_SECRET"] %>
  url: https://api.weixin.qq.com
  callback_url: <%= ENV["MP_CALLBACK_URL"] %>
